kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  selector:
    app: yeoul-home
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeoul-home
  template:
    metadata:
      name: yeoul-home-pod
      labels:
        app: yeoul-home #Service의 selecotr 의 app:yeoul-home 과 일치해야함.
    spec:
      containers:
      - name: yeoul-nodejs
        image: gcr.io/${GOOGLE_PROJECT_ID}/nodejs:${CIRCLE_SHA1}
        ports:
        - name: http
          containerPort: 4000
          protocol: TCP
