kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}
spec:
  selector:
    app: ${PROJECT_NAME}
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer
---
apiVersion: app/node-js
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: {$PROJECT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
      - name: ${PROJECT_NAME}
        image: gcr.io/${GOOGLE_PROJECT_ID}/nodejs:$TAG
        command: 
        ports:
        - name: http
          containerPort: 4000
          protocol: TCP
